name: Deploy to Develop Workspace

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    name: Deploy-Development-Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform workspace select Develop
          terraform plan -out=tfplan
        continue-on-error: true

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        run: |
          terraform workspace select Develop
          terraform apply -auto-approve tfplan
